import { auth, db } from "./firebase-config.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { collection, deleteDoc, doc, getDoc, getDocs, onSnapshot, query, serverTimestamp, setDoc, updateDoc, where } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
let user=null,settings={},following=new Set(),profile={};const processed=new Set(),hidden=new Set(JSON.parse(localStorage.getItem("anonchat-hidden-posts")||"[]"));
const feed=document.getElementById("feed"),composer=document.getElementById("post-content");
const saveDraft=()=>user&&localStorage.setItem("anonchat-timeline-draft-"+user.uid,composer.value);
const showMessage=m=>{const s=document.getElementById("timeline-status");if(s)s.textContent=m};
if(composer){composer.addEventListener("input",()=>{clearTimeout(window.timelineDraftTimer);window.timelineDraftTimer=setTimeout(saveDraft,350)});}
const addHashtags=(item,text)=>{const tags=[...new Set((text.match(/#[A-Za-z0-9_]+/g)||[]).slice(0,8))];if(!tags.length)return;const row=document.createElement("div");row.className="hashtag-row";tags.forEach(tag=>{const b=document.createElement("button");b.type="button";b.textContent=tag;b.onclick=()=>{const search=document.getElementById("site-search");if(search){search.value=tag.slice(1);search.dispatchEvent(new Event("input"));search.focus();}};row.append(b)});item.append(row)};
const settingsAllow=(data,authorId)=>{if(settings.hideReposts&&data.type==="repost")return false;if((settings.mutedKeywords||[]).some(k=>k&&String(data.content||"").toLowerCase().includes(k.toLowerCase())))return false;if(settings.feedMode==="following"&&authorId!==user.uid&&!following.has(authorId))return false;if(settings.feedMode==="photos"&&!data.imageData)return false;if(settings.feedMode==="questions"&&!String(data.content||"").includes("?")&&data.category!=="Question")return false;return true};
const enhance=async item=>{if(!user||processed.has(item.id)||!item.id.startsWith("post-"))return;processed.add(item.id);const postId=item.id.slice(5),snap=await getDoc(doc(db,"posts",postId));if(!snap.exists())return;const data=snap.data(),authorId=data.type==="repost"?data.originalAuthorId:data.authorId;if(hidden.has(postId)||!settingsAllow(data,authorId)){item.hidden=true;return}
if(data.contentWarning&&settings.contentWarnings!==false){const text=item.querySelector("p:not(.repost-label)");if(text){text.hidden=true;const warning=document.createElement("button");warning.className="content-warning-button";warning.textContent="Content warning: "+data.contentWarning+" · Show";warning.onclick=()=>{text.hidden=!text.hidden;warning.textContent=text.hidden?"Content warning: "+data.contentWarning+" · Show":"Hide warned content"};item.insertBefore(warning,text)}}
addHashtags(item,String(data.content||""));const bar=document.createElement("div");bar.className="extra-post-actions";
const bookmark=document.createElement("button");bookmark.type="button";bookmark.textContent="🔖 Save";const bookmarkRef=doc(db,"bookmarks",user.uid+"_"+postId);getDoc(bookmarkRef).then(x=>{if(x.exists())bookmark.textContent="🔖 Saved"});bookmark.onclick=async()=>{const x=await getDoc(bookmarkRef);if(x.exists()){await deleteDoc(bookmarkRef);bookmark.textContent="🔖 Save"}else{const note=prompt("Optional private note for this saved post:")||"";await setDoc(bookmarkRef,{uid:user.uid,postId,note,createdAt:serverTimestamp()});bookmark.textContent="🔖 Saved"}};
const why=document.createElement("button");why.type="button";why.textContent="Why this post?";why.onclick=()=>alert(data.type==="repost"?"This appeared because someone shared it to the public timeline.":following.has(authorId)?"This appeared in the timeline from an account you follow.":"This appeared because it is a recent public AnonChat post.");
const hide=document.createElement("button");hide.type="button";hide.textContent="Not interested";hide.onclick=()=>{hidden.add(postId);localStorage.setItem("anonchat-hidden-posts",JSON.stringify([...hidden]));item.hidden=true};
bar.append(bookmark,why,hide);
if(item.querySelector(".delete-button")){const age=Date.now()-(data.createdAt?.toMillis?.()||0);if(age<=900000){const edit=document.createElement("button");edit.type="button";edit.textContent="Edit";edit.onclick=async()=>{const next=prompt("Edit your post:",data.content)?.trim();if(next&&next!==data.content){await updateDoc(doc(db,"posts",postId),{content:next,editedAt:serverTimestamp()});showMessage("Post edited.")}};bar.append(edit)}
const pin=document.createElement("button");pin.type="button";pin.textContent=(profile.pinnedPostIds||[]).includes(postId)?"Unpin":"Pin";pin.onclick=async()=>{const pins=[...(profile.pinnedPostIds||[])],i=pins.indexOf(postId);if(i>=0)pins.splice(i,1);else{if(pins.length>=3)pins.shift();pins.push(postId)}await updateDoc(doc(db,"users",user.uid),{pinnedPostIds:pins});profile.pinnedPostIds=pins;pin.textContent=pins.includes(postId)?"Unpin":"Pin"};bar.append(pin)}
if("Translator" in window){const translate=document.createElement("button");translate.type="button";translate.textContent="Translate";translate.onclick=async()=>{try{const target=navigator.language.split("-")[0],translator=await window.Translator.create({sourceLanguage:"auto",targetLanguage:target}),translated=await translator.translate(data.content);alert(translated)}catch{showMessage("Translation is unavailable in this browser.")}};bar.append(translate)}
item.append(bar)};
const scan=()=>feed&&[...feed.children].forEach(enhance);if(feed)new MutationObserver(scan).observe(feed,{childList:true});
onAuthStateChanged(auth,async current=>{if(!current)return;user=current;const p=await getDoc(doc(db,"users",user.uid));profile=p.data()||{};const draft=localStorage.getItem("anonchat-timeline-draft-"+user.uid);if(composer&&draft&&!composer.value)composer.value=draft;onSnapshot(doc(db,"userSettings",user.uid),s=>{settings=s.exists()?s.data():{};processed.clear();[...feed.children].forEach(x=>x.hidden=false);scan()});const fs=await getDocs(query(collection(db,"follows"),where("followerId","==",user.uid)));following=new Set(fs.docs.map(x=>x.data().followingId));const profileLink=document.getElementById("menu-profile-link");if(profileLink)profileLink.href="profile.html?uid="+encodeURIComponent(user.uid);scan()});